### ISSUE TITLE
Error handler

### ISSUE THREAD

**Issue by gagle** [hapijs/good-reporter#23]
How should we handle the errors happening inside the `_report` function?

**Comment by arb** [comment]
That is the responsibility of the individual good-reporter implementations. I'd probably just log it to the error stream. If it's like something that you can't recover from, maybe disconnect the "report" event handler like https://github.com/hapijs/good-file/blob/master/lib/index.js#L130-L136. 

If you think the error is serve enough, I guess you could throw the error and let the process restart?
