### ISSUE TITLE
Constructor doesn't check for inheritance properly

### ISSUE THREAD

**Issue by yonjah** [hapijs/good-reporter#25]
https://github.com/hapijs/good-reporter/blob/master/lib/index.js#L35

```javascript
Hoek.assert(this.constructor === internals.GoodReporter
        || this.constructor.super_ === internals.GoodReporter, 'GoodReporter must be created with new');
```

this is ok as long as you don't inherit from another reporter like =
```javascript
function BaseReporter () {
    return GoodReporter.apply(this, arguments);
}
Hoek.inherits(BaseReporter, GoodReporter);
//more logic for BaseReporter prototype

function ExtraReporter () {
    return BaseReporter.apply(this, arguments);
}
Hoek.inherits(ExtraReporter, BaseReporter);
//more logic for ExtraReporter prototype

var b = new ExtraReporter(); //this will fail  'GoodReporter must be created with new'
```

I don't know why it was written this way but it seems like the common solution of`instanceof` would be better.

```javascript
Hoek.assert(this instanceof internals.GoodReporter, 'GoodReporter must be created with new');
```

**Comment by arb** [comment]
Yeah you're probably right. Inheriting multiple times like that is unusual in JavaScript because it doesn't work like classical inheritance. 

The problem with changing this now is all the current good-reporter implementations would have to be checked if we make this change. It's *probably* fine, but there is no way to know without testing them all.

This is why this module and approach is going away - to prevent problems like this.

**Comment by yonjah** [comment]
Oh. I just finished implementing a reporter wrapper that will allow me to have more control over logging levels.

So is the whole `good` module is going away ?
Whats going to replace it ?

**Comment by arb** [comment]
https://github.com/hapijs/good/issues/292

**Comment by yonjah** [comment]
Ok so Maybe I should explain myself on that thread since the issues I'm having are all inherently relate to Good inflexible API and I guess changing the API is the best thing.

I still think this and the stop issue should be fixed since breaking changes to Good should give enough time to implementers to update their packages.

**Comment by arb** [comment]
There isn't a `stop` issue. The developer needs to handle it themselves. As for the inheritance thing, if you want to PR for it i'll accept it as a breaking change version.
